language: php

php:
    - 5.4
    - 5.5
    - 5.6
    - 7.0
    - 7.1
    - 7.2
    - 7.3

matrix:
  include:
    - php: hhvm
      dist: trusty
    - php: 5.3
      dist: precise
  allow_failures:
    - php: hhvm

before_script:
    - composer install --dev --prefer-dist --no-interaction

script:
    - ./vendor/bin/phpunit --coverage-text
